- hosts: dev
  sudo: yes
  tasks:
  - name: Add HipChat source list
    file: path=/etc/apt/sources.list.d/atlassian-hipchat.list state=touch
  - name: Append HipChat repository in source list
    lineinfile: dest=/etc/apt/sources.list.d/atlassian-hipchat.list line='deb http://downloads.hipchat.com/linux/apt stable main'
  - name: Add HipChat apt-key
    apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key state=present
  - name: apt-get update
    apt: update_cache=yes
  - name: Install hipchat
    apt: name=hipchat state=present
