- hosts: dev
  sudo: yes
  tasks:
  - name: Add PyCharm source list
    file: path=/etc/apt/sources.list.d/jetbrains-pycharm.list state=touch
  - name: Append PyCharm repository in source list
    lineinfile: dest=/etc/apt/sources.list.d/jetbrains-pycharm.list line='deb http://archive.getdeb.net/ubuntu trusty-getdeb apps'
  - name: Add PyCharm apt-key
    apt_key: url=http://archive.getdeb.net/getdeb-archive.key state=present
  - name: apt-get update
    apt: update_cache=yes
  - name: Install pycharm
    apt: name=pycharm state=present
