- hosts: dev
  sudo: yes
  tasks:
  - name: Add sublime-text ppa
    apt_repository: repo=ppa:webupd8team/sublime-text-2 state=present
  - name: apt-get update
    apt: update_cache=yes
  - name: Install sublime-text
    apt: name=sublime-text state=present
