- hosts: dev
  sudo: yes
  tasks:
  - name: apt-get update
    apt: update_cache=yes
  - name: Install vim
    apt: name=vim state=present
  - name: Append :set number in vimrc
    lineinfile: dest=/etc/vim/vimrc line=':set number'
  - name: Append colorscheme elflord in vimrc
    lineinfile: dest=/etc/vim/vimrc line='colorscheme elflord'
